default: &default
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
