
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  # <<: *default
  # database: home_development
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: home_test

production:
  <<: *default
  database: home_production
  username: home
  password: <%= ENV['HOME_DATABASE_PASSWORD'] %>
